server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /health {
        default_type application/json;
        try_files /health/index.json =404;
        add_header Cache-Control "no-cache, no-store";
    }

    location /health/live {
        default_type application/json;
        try_files /health/live.json =404;
        add_header Cache-Control "no-cache, no-store";
    }

    location /health/ready {
        default_type application/json;
        try_files /health/ready.json =404;
        add_header Cache-Control "no-cache, no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
